// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orchestra.Data.Context;

#nullable disable

namespace Orchestra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519225529_Fix")]
    partial class Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orchestra.Models.BpmnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BpmnItem");
                });

            modelBuilder.Entity("Orchestra.Models.BpmnProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BpmnProcess");
                });

            modelBuilder.Entity("Orchestra.Models.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BpmnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BpmnItemId")
                        .HasColumnType("int");

                    b.Property<int>("BpmnProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BpmnItemId");

                    b.HasIndex("BpmnProcessId");

                    b.ToTable("ProcessStep");
                });

            modelBuilder.Entity("Orchestra.Models.ProcessStep", b =>
                {
                    b.HasOne("Orchestra.Models.BpmnItem", "BpmnItem")
                        .WithMany()
                        .HasForeignKey("BpmnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orchestra.Models.BpmnProcess", "BpmnProcess")
                        .WithMany()
                        .HasForeignKey("BpmnProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BpmnItem");

                    b.Navigation("BpmnProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
