name: Trigger auto deployment for orchestraAdd commentMore actions

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/orchestra-AutoDeployTrigger-1dba7355-803c-42ae-80cc-f16cca7b2736.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORCHESTRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORCHESTRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORCHESTRA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Orchestra
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: orchestra20250622192731.azurecr.io
          registryUsername: ${{ secrets.ORCHESTRA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORCHESTRA_REGISTRY_PASSWORD }}
          containerAppName: orchestra
          resourceGroup: Orchestra-rg
          imageToBuild: orchestra20250622192731.azurecr.io/orchestra:${{ github.sha }}
          _buildArgumentsKey_: |Add commentMore actions
            _buildArgumentsValues_
