name: Trigger auto deployment for orchestra

on:
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/orchestra.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.5'

      - name: Restore dependencies
        run: dotnet restore ./Orchestra/Orchestra.csproj

      - name: Publish
        run: dotnet publish ./Orchestra/Orchestra.csproj -c Release -o ./Orchestra/publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORCHESTRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORCHESTRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORCHESTRA_AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: orchestra20250622192731.azurecr.io
          username: ${{ secrets.ORCHESTRA_REGISTRY_USERNAME }}
          password: ${{ secrets.ORCHESTRA_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Orchestra
          file: ./Orchestra/Dockerfile
          push: true
          tags: orchestra20250622192731.azurecr.io/orchestra:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: orchestra20250622192731.azurecr.io
          registryUsername: ${{ secrets.ORCHESTRA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORCHESTRA_REGISTRY_PASSWORD }}
          containerAppName: orchestra
          resourceGroup: Orchestra-rg
          imageToDeploy: orchestra20250622192731.azurecr.io/orchestra:${{ github.sha }}
